### PR TITLE
Use pre-generated lists of region IDs, supported by https://github.co…

### PR DESCRIPTION
**Pull request by stevage**
…m/TerriaJS/terriajs/pull/1202

### CODE REVIEW

**Comment by kring** [comment]
@stevage do we still need this PR?  Because you added these files to TerriaJS itself right?

**Comment by stevage** [comment]
No, I put them in NationalMap. In this pull request, specifically. :)

**Comment by kring** [comment]
But they're in TerriaJS too right?
https://github.com/TerriaJS/terriajs/tree/master/wwwroot/data/regionids

**Comment by stevage** [comment]
Whoops. I think I only meant to put them in `wwwroot/test/data`.

**Pull request merged**
