### PR TITLE
Webpack for the newui branch

### PR DESCRIPTION
**Pull request by kring**
This is the NationalMap side of TerriaJS/terriajs#1440.

### CODE REVIEW

**Comment by AlexGilleran** [comment]
:+1:

**Comment by kring** [comment]
This branch now also switches to `node-sass` instead of `gulp-ruby-sass`.

**Comment by kring** [comment]
I just added a `gulp diagnose` task to this branch to help us diagnose build problems.  Example output:

```
Have you run `npm install` at least twice?  See https://github.com/npm/npm/issues/10727
TerriaJS is linked.  Have you run `npm install` at least twice in your TerriaJS directory?
Problem with package: accepts
  The application has version 1.3.2
  TerriaJS has version 1.1.4
Problem with package: acorn
  The application has version 1.2.2
  TerriaJS has version 3.0.4
Problem with package: terriajs-cesium
  The application does not link to the package.
  TerriaJS links to the package.
```

**Comment by RacingTadpole** [comment]
Is this ready to be merged?

**Comment by kring** [comment]
If you're asking me, I think it is, yes.

**Pull request merged**
