### PR TITLE
Split the huge nm.json into separate pieces which can be auto merged.

### PR DESCRIPTION
**Pull request by stevage**
The smaller pieces are necessary in order to load in reasonable time
in the DataSourceEditor.
Two scripts are included:

* split-catalog.sh does the initial break-up, preserving order by
  pre-pending a number onto each file name
* merge-catalog.sh recombines the datasources. This should be run after
  any edit to a source file is made. jq is required.

To help remember not to edit nm.json directly, I've invoked the
'--compact-output' flag on jq, which produces unreadable JSON, which
as a friendly side effect makes the output about 30% smaller.

### CODE REVIEW

**Comment by stevage** [comment]
I've also added split-groups.sh and merge-groups.sh. To summarise:

As a once off, you run ./split-catalog.sh and then ./split-groups.sh, which together:

*  break down nm.json into datasources/01_Data.gov.au.json (and 10 more), 
* plus datasources/00_National_Data_Sets/*.json
* and 000_settings.json for the non-catalog settings (starting camera and CORS settings)

After making changes to any of the above, run:

* ./merge-groups.sh to rebuild datasources/00_National_Data_Sets.json; and
* ./merge-catalog.sh to rebuild wwwroot/init/nm.json

I'm happy to automate this in the gulp.js, but that would mean making jq a requirement.

**Comment by kgrochow** [comment]
I think it will need to be in gulp to be viable.  I don't want to have to remember to do a merge.sh every time I fiddle with the init file.  Since the splitting will only happen once we can leave that out and then just take advantage of one of the many gulp plugins for merging json to do the job.

**Comment by stevage** [comment]
If we make jq a devdependency, that would be pretty trivial.

**Comment by kring** [comment]
Looks good, just a couple of suggestions:
* Add the generated files (`nm.json`, `00_National_Data_Sets.json`) to `.gitignore`, otherwise someone (probably me) is guaranteed to accidentally check them in before long.
* Remove `merge-datasources` from the default task and instead add it to `build` and `release`.

**Comment by stevage** [comment]
Good ideas, thanks.

**Pull request merged**
