### PR TITLE
Add WA data using their new (beta) CKAN catalogue.

### PR DESCRIPTION
**Pull request by stevage**
It works well, although a bit slow to load initially.

### CODE REVIEW

**Comment by stevage** [comment]
(FYI @keithmoss @tobybellwood )

**Comment by keithmoss** [comment]
Can I preview in UAT somewhere please? :)

**Comment by stevage** [comment]
[You sure can](http://nationalmap.gov.au/#clean&https://rawgit.com/NICTA/nationalmap/wa-ckan/datasources/11_Western_Australian_Government.json)

**Comment by keithmoss** [comment]
<3 TerriaJS!

Ta Steve

**Comment by keithmoss** [comment]
Follow-up thought -

If we later want to expose other services from here (e.g. WFS), data hosted directly in CKAN (e.g. GeoJSON), or tabular data that's csv-geo-au compliant are there any barriers with how we've configured this now?

**Comment by stevage** [comment]
No, we can very easily combine all those things. I'd suggest (based on experience of other CKANs) being a little careful about naming those formats, particularly with casing. (GeoJSON != geojson etc).

Definitely worth having "csv" and "csv-geo-au" as distinct resource formats, as on data.gov.au.

**Pull request merged**
