### PR TITLE
Add a prominent link to the preview of the new UI

### PR DESCRIPTION
**Pull request by kring**
image

### CODE REVIEW

**Comment by stevage** [comment]
Suggestion: don't show this if there are any URL arguments.

For instance:

- if following a share link
- if embedded with a `mode=preview`
- if loading a custom init file

I feel like in all those cases, this will just annoy the user who has some particular use case in mind.

**Comment by stevage** [comment]
Also, "Not right now!" --> "No thanks" (or "Maybe later", or just something without the exclamation mark)

**Comment by kring** [comment]
I believe Steve's problem with the button not doing anything is caused by `npm link`.  It ends up with two copies of `knockout`, one in `terriajs` and one in `nationalmap`, which breaks knockout's dependency tracking.  It might be possible to use webpack configuration to remove the duplicated copy of knockout, but mostly we just need to stop using `npm link`.  [npmgitdev](https://www.npmjs.com/package/npmgitdev) is your friend.

**Comment by kring** [comment]
This is ready.

**Pull request merged**
