### PR TITLE
Add `gulp validate` schema validation.

### PR DESCRIPTION
**Pull request by stevage**
Lots of work to get to this point, but the upshot here is there is now a command `gulp validate` which validates all the config files, using the [terriajs-schema](github.com/TerriaJS/terriajs-schema) module.

That's installed as a devdependency, from Github, so it will always be up to date. (Later versions of the schema go into subdirectories...)

### CODE REVIEW

**Comment by stevage** [comment]
Let's pause this till I resolve validation feedback issues.

**Comment by RacingTadpole** [comment]
This looks very nice. One initial question - when I run `gulp validate` I get the output:

```...
Starting 'validate'...
2.0.0
FAILED: wwwroot/init/nm.json:
1 catalog files failed validation.
[14:05:13] Finished 'validate' after 20 s```

Is there a way to see what the failure was caused by?

**Comment by RacingTadpole** [comment]
Apart from that suggestion, this all looks great to me. A really useful feature, and it looks like it's taken a serious slog to make it work - thanks!

**Comment by RacingTadpole** [comment]
OK, I'm getting much more detailed output now - is this what you expect?
```
Loading schema: ...nationalmap/node_modules/terriajs-schema/schema/2.0.1/Catalog.json ... Schema loaded.
...
OK:     wwwroot/init/tas.json
FAILED: wwwroot/init/test.json:
OK:     wwwroot/init/tind.json
...
```

**Comment by stevage** [comment]
Gah, that's not "detailed" - should tell you what the failure was. Did you `npm install` the latest schema validator? (It should now print out its version, too)

**Comment by RacingTadpole** [comment]
Ah, my mistake. That fixes it nicely:
```
FAILED: wwwroot/init/test.json:
  type instance.catalog[1].items[4].items[2].data is not of a type(s) object
    Value: [{"id":"document","version":"1.0"},{"position":{"cartographicDegrees":[133,-25,0]},"point":{"pixelSize":5,"color":{"rgba":[255,0,0,255]}}}]
```

**Pull request merged**
