### PR TITLE
add purge to varnish script

### PR DESCRIPTION
**Pull request by kgrochow**
Simple purge functionality in varnish script.
Will only allow purge from localhost so there's no new external danger from this.  Other ip addresses will need to be added to the acl purge section to allow purging from other sites.  e.g. Nicta subnet, etc.

### CODE REVIEW

**Comment by kring** [comment]
@peterhassall mind reviewing this?  You're probably the most qualified.

**Comment by peterhassall** [comment]
While this won't work behind a load balancer, it's still useful in a single-instance environment. I've updated the syntax to that recommended by Varnish 3 which ships with Ubuntu 14.04 LTS.

**Comment by kring** [comment]
@kgrochow do you want to look at Peter's changes before I merge this?

**Comment by kring** [comment]
(And thanks for the review, @peterhassall!)

**Comment by kgrochow** [comment]
I peeked earlier.  All looks fine by me.

**Pull request merged**
