### PR TITLE
Catalogue updates

### PR DESCRIPTION
**Pull request by kring**
* Retired the NICTA-hosted geotopo250k data sets, replacing them with the Geoscience Australia Topography data sets (@stevage did all the work on this).
* Improved the metadata, including descriptions and licence information, for many of the data sets in National Data Sets.
* Removed the Topography group under Data Providers.

The Surface Water group could use a better organization, but it's not obvious to me what it should be.

Don't merge this until we're ready to jump over to the new GA datasets, of course.

It's up on the research server here:
http://nationalmap.research.nicta.com.au/demo/

### CODE REVIEW

**Comment by kgrochow** [comment]
We still haven't heard back on performance issues and comms sign-off on GA datasets, so this should wait until that is clarified.

**Comment by kring** [comment]
Yep, agreed.

**Comment by kring** [comment]
For my future reference in keeping catalogues in sync: this branch is missing the new Catchment Scale Land Use 2015 layer.  It also seems to be missing the Water Observations from Space datasets.

**Comment by kring** [comment]
These changes are now in the `ga-new-datasources` branch.

**Pull request closed without merging**
