### PR TITLE
Ga server

### PR DESCRIPTION
**Pull request by stevage**
* Updated all Geoscience Australia layers to point to the new infrastructure at http://services.ga.gov.au/gis/rest/services .

### CODE REVIEW

**Comment by kring** [comment]
`Habitation -> Place Names` references a bunch of layer names that don't actually exist.  Looks like some of them have just changed name.

**Comment by stevage** [comment]
I've alerted GA, who will investigate and see if there are any other similar cases.

**Comment by kring** [comment]
I went through all the layers, and didn't see any problems other than the missing NoData.

**Comment by stevage** [comment]
Updated list [here](https://docs.google.com/spreadsheets/d/1f78gKCpXmwH2egSY0a2Jfl0cLZSsWkz4MSLBxfWkelI/edit#gid=411736129).

**Pull request merged**
